/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as StaffLayoutRouteImport } from './routes/staff/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as StaffLayoutIndexRouteImport } from './routes/staff/_layout/index'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as StaffLayoutPoisRouteImport } from './routes/staff/_layout/pois'
import { Route as StaffLayoutLocationsRouteImport } from './routes/staff/_layout/locations'
import { Route as StaffLayoutAdvertisementsRouteImport } from './routes/staff/_layout/advertisements'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AdminLayoutSubscriptionsRouteImport } from './routes/admin/_layout/subscriptions'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin/_layout/settings'
import { Route as AdminLayoutDestinationsRouteImport } from './routes/admin/_layout/destinations'
import { Route as AdminLayoutBookingsRouteImport } from './routes/admin/_layout/bookings'
import { Route as AdminLayoutAnalyticsRouteImport } from './routes/admin/_layout/analytics'
import { Route as AdminLayoutAccountsRouteImport } from './routes/admin/_layout/accounts'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as StaffLayoutPoisIdRouteImport } from './routes/staff/_layout/pois.$id'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLayoutRoute = StaffLayoutRouteImport.update({
  id: '/staff/_layout',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLayoutIndexRoute = StaffLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffLayoutRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const StaffLayoutPoisRoute = StaffLayoutPoisRouteImport.update({
  id: '/pois',
  path: '/pois',
  getParentRoute: () => StaffLayoutRoute,
} as any)
const StaffLayoutLocationsRoute = StaffLayoutLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => StaffLayoutRoute,
} as any)
const StaffLayoutAdvertisementsRoute =
  StaffLayoutAdvertisementsRouteImport.update({
    id: '/advertisements',
    path: '/advertisements',
    getParentRoute: () => StaffLayoutRoute,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutSubscriptionsRoute =
  AdminLayoutSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDestinationsRoute = AdminLayoutDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBookingsRoute = AdminLayoutBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAnalyticsRoute = AdminLayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAccountsRoute = AdminLayoutAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLayoutPoisIdRoute = StaffLayoutPoisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffLayoutPoisRoute,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/staff': typeof StaffLayoutRouteWithChildren
  '/staff/login': typeof StaffLoginRoute
  '/admin/accounts': typeof AdminLayoutAccountsRoute
  '/admin/analytics': typeof AdminLayoutAnalyticsRoute
  '/admin/bookings': typeof AdminLayoutBookingsRoute
  '/admin/destinations': typeof AdminLayoutDestinationsRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/subscriptions': typeof AdminLayoutSubscriptionsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/staff/advertisements': typeof StaffLayoutAdvertisementsRoute
  '/staff/locations': typeof StaffLayoutLocationsRoute
  '/staff/pois': typeof StaffLayoutPoisRouteWithChildren
  '/admin/': typeof AdminLayoutIndexRoute
  '/staff/': typeof StaffLayoutIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/staff/pois/$id': typeof StaffLayoutPoisIdRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/staff/login': typeof StaffLoginRoute
  '/admin/accounts': typeof AdminLayoutAccountsRoute
  '/admin/analytics': typeof AdminLayoutAnalyticsRoute
  '/admin/bookings': typeof AdminLayoutBookingsRoute
  '/admin/destinations': typeof AdminLayoutDestinationsRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/subscriptions': typeof AdminLayoutSubscriptionsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/staff/advertisements': typeof StaffLayoutAdvertisementsRoute
  '/staff/locations': typeof StaffLayoutLocationsRoute
  '/staff/pois': typeof StaffLayoutPoisRouteWithChildren
  '/admin': typeof AdminLayoutIndexRoute
  '/staff': typeof StaffLayoutIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/staff/pois/$id': typeof StaffLayoutPoisIdRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/staff/_layout': typeof StaffLayoutRouteWithChildren
  '/staff/login': typeof StaffLoginRoute
  '/admin/_layout/accounts': typeof AdminLayoutAccountsRoute
  '/admin/_layout/analytics': typeof AdminLayoutAnalyticsRoute
  '/admin/_layout/bookings': typeof AdminLayoutBookingsRoute
  '/admin/_layout/destinations': typeof AdminLayoutDestinationsRoute
  '/admin/_layout/settings': typeof AdminLayoutSettingsRoute
  '/admin/_layout/subscriptions': typeof AdminLayoutSubscriptionsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/staff/_layout/advertisements': typeof StaffLayoutAdvertisementsRoute
  '/staff/_layout/locations': typeof StaffLayoutLocationsRoute
  '/staff/_layout/pois': typeof StaffLayoutPoisRouteWithChildren
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/staff/_layout/': typeof StaffLayoutIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/staff/_layout/pois/$id': typeof StaffLayoutPoisIdRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/staff'
    | '/staff/login'
    | '/admin/accounts'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/destinations'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/staff/advertisements'
    | '/staff/locations'
    | '/staff/pois'
    | '/admin/'
    | '/staff/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/staff/pois/$id'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/staff/login'
    | '/admin/accounts'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/destinations'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/staff/advertisements'
    | '/staff/locations'
    | '/staff/pois'
    | '/admin'
    | '/staff'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/staff/pois/$id'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/admin/_layout'
    | '/admin/login'
    | '/staff/_layout'
    | '/staff/login'
    | '/admin/_layout/accounts'
    | '/admin/_layout/analytics'
    | '/admin/_layout/bookings'
    | '/admin/_layout/destinations'
    | '/admin/_layout/settings'
    | '/admin/_layout/subscriptions'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/staff/_layout/advertisements'
    | '/staff/_layout/locations'
    | '/staff/_layout/pois'
    | '/admin/_layout/'
    | '/staff/_layout/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/staff/_layout/pois/$id'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  StaffLayoutRoute: typeof StaffLayoutRouteWithChildren
  StaffLoginRoute: typeof StaffLoginRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/_layout': {
      id: '/staff/_layout'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/_layout/': {
      id: '/staff/_layout/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffLayoutIndexRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/staff/_layout/pois': {
      id: '/staff/_layout/pois'
      path: '/pois'
      fullPath: '/staff/pois'
      preLoaderRoute: typeof StaffLayoutPoisRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/staff/_layout/locations': {
      id: '/staff/_layout/locations'
      path: '/locations'
      fullPath: '/staff/locations'
      preLoaderRoute: typeof StaffLayoutLocationsRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/staff/_layout/advertisements': {
      id: '/staff/_layout/advertisements'
      path: '/advertisements'
      fullPath: '/staff/advertisements'
      preLoaderRoute: typeof StaffLayoutAdvertisementsRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/subscriptions': {
      id: '/admin/_layout/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminLayoutSubscriptionsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/settings': {
      id: '/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/destinations': {
      id: '/admin/_layout/destinations'
      path: '/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AdminLayoutDestinationsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/bookings': {
      id: '/admin/_layout/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminLayoutBookingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/analytics': {
      id: '/admin/_layout/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminLayoutAnalyticsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/accounts': {
      id: '/admin/_layout/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminLayoutAccountsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/_layout/pois/$id': {
      id: '/staff/_layout/pois/$id'
      path: '/$id'
      fullPath: '/staff/pois/$id'
      preLoaderRoute: typeof StaffLayoutPoisIdRouteImport
      parentRoute: typeof StaffLayoutPoisRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutAccountsRoute: typeof AdminLayoutAccountsRoute
  AdminLayoutAnalyticsRoute: typeof AdminLayoutAnalyticsRoute
  AdminLayoutBookingsRoute: typeof AdminLayoutBookingsRoute
  AdminLayoutDestinationsRoute: typeof AdminLayoutDestinationsRoute
  AdminLayoutSettingsRoute: typeof AdminLayoutSettingsRoute
  AdminLayoutSubscriptionsRoute: typeof AdminLayoutSubscriptionsRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAccountsRoute: AdminLayoutAccountsRoute,
  AdminLayoutAnalyticsRoute: AdminLayoutAnalyticsRoute,
  AdminLayoutBookingsRoute: AdminLayoutBookingsRoute,
  AdminLayoutDestinationsRoute: AdminLayoutDestinationsRoute,
  AdminLayoutSettingsRoute: AdminLayoutSettingsRoute,
  AdminLayoutSubscriptionsRoute: AdminLayoutSubscriptionsRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface StaffLayoutPoisRouteChildren {
  StaffLayoutPoisIdRoute: typeof StaffLayoutPoisIdRoute
}

const StaffLayoutPoisRouteChildren: StaffLayoutPoisRouteChildren = {
  StaffLayoutPoisIdRoute: StaffLayoutPoisIdRoute,
}

const StaffLayoutPoisRouteWithChildren = StaffLayoutPoisRoute._addFileChildren(
  StaffLayoutPoisRouteChildren,
)

interface StaffLayoutRouteChildren {
  StaffLayoutAdvertisementsRoute: typeof StaffLayoutAdvertisementsRoute
  StaffLayoutLocationsRoute: typeof StaffLayoutLocationsRoute
  StaffLayoutPoisRoute: typeof StaffLayoutPoisRouteWithChildren
  StaffLayoutIndexRoute: typeof StaffLayoutIndexRoute
}

const StaffLayoutRouteChildren: StaffLayoutRouteChildren = {
  StaffLayoutAdvertisementsRoute: StaffLayoutAdvertisementsRoute,
  StaffLayoutLocationsRoute: StaffLayoutLocationsRoute,
  StaffLayoutPoisRoute: StaffLayoutPoisRouteWithChildren,
  StaffLayoutIndexRoute: StaffLayoutIndexRoute,
}

const StaffLayoutRouteWithChildren = StaffLayoutRoute._addFileChildren(
  StaffLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  StaffLayoutRoute: StaffLayoutRouteWithChildren,
  StaffLoginRoute: StaffLoginRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
