/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnerLoginRouteImport } from './routes/partner/login'
import { Route as PartnerLayoutRouteImport } from './routes/partner/_layout'
import { Route as ManagerLoginRouteImport } from './routes/manager/login'
import { Route as ManagerLayoutRouteImport } from './routes/manager/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as PartnerLayoutIndexRouteImport } from './routes/partner/_layout/index'
import { Route as ManagerLayoutIndexRouteImport } from './routes/manager/_layout/index'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as PartnerLayoutStatsRouteImport } from './routes/partner/_layout/stats'
import { Route as PartnerLayoutProfileRouteImport } from './routes/partner/_layout/profile'
import { Route as PartnerLayoutPoiRouteImport } from './routes/partner/_layout/poi'
import { Route as PartnerLayoutPackagesRouteImport } from './routes/partner/_layout/packages'
import { Route as PartnerLayoutHistoryRouteImport } from './routes/partner/_layout/history'
import { Route as PartnerLayoutAdvertisementRouteImport } from './routes/partner/_layout/advertisement'
import { Route as ManagerLayoutPoisRouteImport } from './routes/manager/_layout/pois'
import { Route as ManagerLayoutPartnerRequestsRouteImport } from './routes/manager/_layout/partner-requests'
import { Route as ManagerLayoutLocationsRouteImport } from './routes/manager/_layout/locations'
import { Route as ManagerLayoutAdvertisementsRouteImport } from './routes/manager/_layout/advertisements'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AdminLayoutTransactionsRouteImport } from './routes/admin/_layout/transactions'
import { Route as AdminLayoutSubscriptionsRouteImport } from './routes/admin/_layout/subscriptions'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin/_layout/settings'
import { Route as AdminLayoutProfileRouteImport } from './routes/admin/_layout/profile'
import { Route as AdminLayoutDestinationsRouteImport } from './routes/admin/_layout/destinations'
import { Route as AdminLayoutBookingsRouteImport } from './routes/admin/_layout/bookings'
import { Route as AdminLayoutAnalyticsRouteImport } from './routes/admin/_layout/analytics'
import { Route as AdminLayoutAccountsRouteImport } from './routes/admin/_layout/accounts'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as ManagerLayoutPoisIdRouteImport } from './routes/manager/_layout/pois.$id'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerLoginRoute = PartnerLoginRouteImport.update({
  id: '/partner/login',
  path: '/partner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerLayoutRoute = PartnerLayoutRouteImport.update({
  id: '/partner/_layout',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerLoginRoute = ManagerLoginRouteImport.update({
  id: '/manager/login',
  path: '/manager/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerLayoutRoute = ManagerLayoutRouteImport.update({
  id: '/manager/_layout',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerLayoutIndexRoute = PartnerLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerLayoutRoute,
} as any)
const ManagerLayoutIndexRoute = ManagerLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerLayoutRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const PartnerLayoutStatsRoute = PartnerLayoutStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PartnerLayoutRoute,
} as any)
const PartnerLayoutProfileRoute = PartnerLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PartnerLayoutRoute,
} as any)
const PartnerLayoutPoiRoute = PartnerLayoutPoiRouteImport.update({
  id: '/poi',
  path: '/poi',
  getParentRoute: () => PartnerLayoutRoute,
} as any)
const PartnerLayoutPackagesRoute = PartnerLayoutPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => PartnerLayoutRoute,
} as any)
const PartnerLayoutHistoryRoute = PartnerLayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PartnerLayoutRoute,
} as any)
const PartnerLayoutAdvertisementRoute =
  PartnerLayoutAdvertisementRouteImport.update({
    id: '/advertisement',
    path: '/advertisement',
    getParentRoute: () => PartnerLayoutRoute,
  } as any)
const ManagerLayoutPoisRoute = ManagerLayoutPoisRouteImport.update({
  id: '/pois',
  path: '/pois',
  getParentRoute: () => ManagerLayoutRoute,
} as any)
const ManagerLayoutPartnerRequestsRoute =
  ManagerLayoutPartnerRequestsRouteImport.update({
    id: '/partner-requests',
    path: '/partner-requests',
    getParentRoute: () => ManagerLayoutRoute,
  } as any)
const ManagerLayoutLocationsRoute = ManagerLayoutLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => ManagerLayoutRoute,
} as any)
const ManagerLayoutAdvertisementsRoute =
  ManagerLayoutAdvertisementsRouteImport.update({
    id: '/advertisements',
    path: '/advertisements',
    getParentRoute: () => ManagerLayoutRoute,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutTransactionsRoute = AdminLayoutTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSubscriptionsRoute =
  AdminLayoutSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutProfileRoute = AdminLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDestinationsRoute = AdminLayoutDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBookingsRoute = AdminLayoutBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAnalyticsRoute = AdminLayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAccountsRoute = AdminLayoutAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerLayoutPoisIdRoute = ManagerLayoutPoisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ManagerLayoutPoisRoute,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/manager': typeof ManagerLayoutRouteWithChildren
  '/manager/login': typeof ManagerLoginRoute
  '/partner': typeof PartnerLayoutRouteWithChildren
  '/partner/login': typeof PartnerLoginRoute
  '/admin/accounts': typeof AdminLayoutAccountsRoute
  '/admin/analytics': typeof AdminLayoutAnalyticsRoute
  '/admin/bookings': typeof AdminLayoutBookingsRoute
  '/admin/destinations': typeof AdminLayoutDestinationsRoute
  '/admin/profile': typeof AdminLayoutProfileRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/subscriptions': typeof AdminLayoutSubscriptionsRoute
  '/admin/transactions': typeof AdminLayoutTransactionsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/manager/advertisements': typeof ManagerLayoutAdvertisementsRoute
  '/manager/locations': typeof ManagerLayoutLocationsRoute
  '/manager/partner-requests': typeof ManagerLayoutPartnerRequestsRoute
  '/manager/pois': typeof ManagerLayoutPoisRouteWithChildren
  '/partner/advertisement': typeof PartnerLayoutAdvertisementRoute
  '/partner/history': typeof PartnerLayoutHistoryRoute
  '/partner/packages': typeof PartnerLayoutPackagesRoute
  '/partner/poi': typeof PartnerLayoutPoiRoute
  '/partner/profile': typeof PartnerLayoutProfileRoute
  '/partner/stats': typeof PartnerLayoutStatsRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/manager/': typeof ManagerLayoutIndexRoute
  '/partner/': typeof PartnerLayoutIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/manager/pois/$id': typeof ManagerLayoutPoisIdRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/manager/login': typeof ManagerLoginRoute
  '/partner/login': typeof PartnerLoginRoute
  '/admin/accounts': typeof AdminLayoutAccountsRoute
  '/admin/analytics': typeof AdminLayoutAnalyticsRoute
  '/admin/bookings': typeof AdminLayoutBookingsRoute
  '/admin/destinations': typeof AdminLayoutDestinationsRoute
  '/admin/profile': typeof AdminLayoutProfileRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/subscriptions': typeof AdminLayoutSubscriptionsRoute
  '/admin/transactions': typeof AdminLayoutTransactionsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/manager/advertisements': typeof ManagerLayoutAdvertisementsRoute
  '/manager/locations': typeof ManagerLayoutLocationsRoute
  '/manager/partner-requests': typeof ManagerLayoutPartnerRequestsRoute
  '/manager/pois': typeof ManagerLayoutPoisRouteWithChildren
  '/partner/advertisement': typeof PartnerLayoutAdvertisementRoute
  '/partner/history': typeof PartnerLayoutHistoryRoute
  '/partner/packages': typeof PartnerLayoutPackagesRoute
  '/partner/poi': typeof PartnerLayoutPoiRoute
  '/partner/profile': typeof PartnerLayoutProfileRoute
  '/partner/stats': typeof PartnerLayoutStatsRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/manager': typeof ManagerLayoutIndexRoute
  '/partner': typeof PartnerLayoutIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/manager/pois/$id': typeof ManagerLayoutPoisIdRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/manager/_layout': typeof ManagerLayoutRouteWithChildren
  '/manager/login': typeof ManagerLoginRoute
  '/partner/_layout': typeof PartnerLayoutRouteWithChildren
  '/partner/login': typeof PartnerLoginRoute
  '/admin/_layout/accounts': typeof AdminLayoutAccountsRoute
  '/admin/_layout/analytics': typeof AdminLayoutAnalyticsRoute
  '/admin/_layout/bookings': typeof AdminLayoutBookingsRoute
  '/admin/_layout/destinations': typeof AdminLayoutDestinationsRoute
  '/admin/_layout/profile': typeof AdminLayoutProfileRoute
  '/admin/_layout/settings': typeof AdminLayoutSettingsRoute
  '/admin/_layout/subscriptions': typeof AdminLayoutSubscriptionsRoute
  '/admin/_layout/transactions': typeof AdminLayoutTransactionsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/manager/_layout/advertisements': typeof ManagerLayoutAdvertisementsRoute
  '/manager/_layout/locations': typeof ManagerLayoutLocationsRoute
  '/manager/_layout/partner-requests': typeof ManagerLayoutPartnerRequestsRoute
  '/manager/_layout/pois': typeof ManagerLayoutPoisRouteWithChildren
  '/partner/_layout/advertisement': typeof PartnerLayoutAdvertisementRoute
  '/partner/_layout/history': typeof PartnerLayoutHistoryRoute
  '/partner/_layout/packages': typeof PartnerLayoutPackagesRoute
  '/partner/_layout/poi': typeof PartnerLayoutPoiRoute
  '/partner/_layout/profile': typeof PartnerLayoutProfileRoute
  '/partner/_layout/stats': typeof PartnerLayoutStatsRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/manager/_layout/': typeof ManagerLayoutIndexRoute
  '/partner/_layout/': typeof PartnerLayoutIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/manager/_layout/pois/$id': typeof ManagerLayoutPoisIdRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/manager'
    | '/manager/login'
    | '/partner'
    | '/partner/login'
    | '/admin/accounts'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/destinations'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/manager/advertisements'
    | '/manager/locations'
    | '/manager/partner-requests'
    | '/manager/pois'
    | '/partner/advertisement'
    | '/partner/history'
    | '/partner/packages'
    | '/partner/poi'
    | '/partner/profile'
    | '/partner/stats'
    | '/admin/'
    | '/manager/'
    | '/partner/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/manager/pois/$id'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/manager/login'
    | '/partner/login'
    | '/admin/accounts'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/destinations'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/manager/advertisements'
    | '/manager/locations'
    | '/manager/partner-requests'
    | '/manager/pois'
    | '/partner/advertisement'
    | '/partner/history'
    | '/partner/packages'
    | '/partner/poi'
    | '/partner/profile'
    | '/partner/stats'
    | '/admin'
    | '/manager'
    | '/partner'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/manager/pois/$id'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/admin/_layout'
    | '/admin/login'
    | '/manager/_layout'
    | '/manager/login'
    | '/partner/_layout'
    | '/partner/login'
    | '/admin/_layout/accounts'
    | '/admin/_layout/analytics'
    | '/admin/_layout/bookings'
    | '/admin/_layout/destinations'
    | '/admin/_layout/profile'
    | '/admin/_layout/settings'
    | '/admin/_layout/subscriptions'
    | '/admin/_layout/transactions'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/manager/_layout/advertisements'
    | '/manager/_layout/locations'
    | '/manager/_layout/partner-requests'
    | '/manager/_layout/pois'
    | '/partner/_layout/advertisement'
    | '/partner/_layout/history'
    | '/partner/_layout/packages'
    | '/partner/_layout/poi'
    | '/partner/_layout/profile'
    | '/partner/_layout/stats'
    | '/admin/_layout/'
    | '/manager/_layout/'
    | '/partner/_layout/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/manager/_layout/pois/$id'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ManagerLayoutRoute: typeof ManagerLayoutRouteWithChildren
  ManagerLoginRoute: typeof ManagerLoginRoute
  PartnerLayoutRoute: typeof PartnerLayoutRouteWithChildren
  PartnerLoginRoute: typeof PartnerLoginRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/login': {
      id: '/partner/login'
      path: '/partner/login'
      fullPath: '/partner/login'
      preLoaderRoute: typeof PartnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/_layout': {
      id: '/partner/_layout'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/login': {
      id: '/manager/login'
      path: '/manager/login'
      fullPath: '/manager/login'
      preLoaderRoute: typeof ManagerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/_layout': {
      id: '/manager/_layout'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/_layout/': {
      id: '/partner/_layout/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerLayoutIndexRouteImport
      parentRoute: typeof PartnerLayoutRoute
    }
    '/manager/_layout/': {
      id: '/manager/_layout/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerLayoutIndexRouteImport
      parentRoute: typeof ManagerLayoutRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/partner/_layout/stats': {
      id: '/partner/_layout/stats'
      path: '/stats'
      fullPath: '/partner/stats'
      preLoaderRoute: typeof PartnerLayoutStatsRouteImport
      parentRoute: typeof PartnerLayoutRoute
    }
    '/partner/_layout/profile': {
      id: '/partner/_layout/profile'
      path: '/profile'
      fullPath: '/partner/profile'
      preLoaderRoute: typeof PartnerLayoutProfileRouteImport
      parentRoute: typeof PartnerLayoutRoute
    }
    '/partner/_layout/poi': {
      id: '/partner/_layout/poi'
      path: '/poi'
      fullPath: '/partner/poi'
      preLoaderRoute: typeof PartnerLayoutPoiRouteImport
      parentRoute: typeof PartnerLayoutRoute
    }
    '/partner/_layout/packages': {
      id: '/partner/_layout/packages'
      path: '/packages'
      fullPath: '/partner/packages'
      preLoaderRoute: typeof PartnerLayoutPackagesRouteImport
      parentRoute: typeof PartnerLayoutRoute
    }
    '/partner/_layout/history': {
      id: '/partner/_layout/history'
      path: '/history'
      fullPath: '/partner/history'
      preLoaderRoute: typeof PartnerLayoutHistoryRouteImport
      parentRoute: typeof PartnerLayoutRoute
    }
    '/partner/_layout/advertisement': {
      id: '/partner/_layout/advertisement'
      path: '/advertisement'
      fullPath: '/partner/advertisement'
      preLoaderRoute: typeof PartnerLayoutAdvertisementRouteImport
      parentRoute: typeof PartnerLayoutRoute
    }
    '/manager/_layout/pois': {
      id: '/manager/_layout/pois'
      path: '/pois'
      fullPath: '/manager/pois'
      preLoaderRoute: typeof ManagerLayoutPoisRouteImport
      parentRoute: typeof ManagerLayoutRoute
    }
    '/manager/_layout/partner-requests': {
      id: '/manager/_layout/partner-requests'
      path: '/partner-requests'
      fullPath: '/manager/partner-requests'
      preLoaderRoute: typeof ManagerLayoutPartnerRequestsRouteImport
      parentRoute: typeof ManagerLayoutRoute
    }
    '/manager/_layout/locations': {
      id: '/manager/_layout/locations'
      path: '/locations'
      fullPath: '/manager/locations'
      preLoaderRoute: typeof ManagerLayoutLocationsRouteImport
      parentRoute: typeof ManagerLayoutRoute
    }
    '/manager/_layout/advertisements': {
      id: '/manager/_layout/advertisements'
      path: '/advertisements'
      fullPath: '/manager/advertisements'
      preLoaderRoute: typeof ManagerLayoutAdvertisementsRouteImport
      parentRoute: typeof ManagerLayoutRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/transactions': {
      id: '/admin/_layout/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminLayoutTransactionsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/subscriptions': {
      id: '/admin/_layout/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminLayoutSubscriptionsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/settings': {
      id: '/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/profile': {
      id: '/admin/_layout/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminLayoutProfileRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/destinations': {
      id: '/admin/_layout/destinations'
      path: '/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AdminLayoutDestinationsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/bookings': {
      id: '/admin/_layout/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminLayoutBookingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/analytics': {
      id: '/admin/_layout/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminLayoutAnalyticsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/accounts': {
      id: '/admin/_layout/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminLayoutAccountsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/_layout/pois/$id': {
      id: '/manager/_layout/pois/$id'
      path: '/$id'
      fullPath: '/manager/pois/$id'
      preLoaderRoute: typeof ManagerLayoutPoisIdRouteImport
      parentRoute: typeof ManagerLayoutPoisRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutAccountsRoute: typeof AdminLayoutAccountsRoute
  AdminLayoutAnalyticsRoute: typeof AdminLayoutAnalyticsRoute
  AdminLayoutBookingsRoute: typeof AdminLayoutBookingsRoute
  AdminLayoutDestinationsRoute: typeof AdminLayoutDestinationsRoute
  AdminLayoutProfileRoute: typeof AdminLayoutProfileRoute
  AdminLayoutSettingsRoute: typeof AdminLayoutSettingsRoute
  AdminLayoutSubscriptionsRoute: typeof AdminLayoutSubscriptionsRoute
  AdminLayoutTransactionsRoute: typeof AdminLayoutTransactionsRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAccountsRoute: AdminLayoutAccountsRoute,
  AdminLayoutAnalyticsRoute: AdminLayoutAnalyticsRoute,
  AdminLayoutBookingsRoute: AdminLayoutBookingsRoute,
  AdminLayoutDestinationsRoute: AdminLayoutDestinationsRoute,
  AdminLayoutProfileRoute: AdminLayoutProfileRoute,
  AdminLayoutSettingsRoute: AdminLayoutSettingsRoute,
  AdminLayoutSubscriptionsRoute: AdminLayoutSubscriptionsRoute,
  AdminLayoutTransactionsRoute: AdminLayoutTransactionsRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface ManagerLayoutPoisRouteChildren {
  ManagerLayoutPoisIdRoute: typeof ManagerLayoutPoisIdRoute
}

const ManagerLayoutPoisRouteChildren: ManagerLayoutPoisRouteChildren = {
  ManagerLayoutPoisIdRoute: ManagerLayoutPoisIdRoute,
}

const ManagerLayoutPoisRouteWithChildren =
  ManagerLayoutPoisRoute._addFileChildren(ManagerLayoutPoisRouteChildren)

interface ManagerLayoutRouteChildren {
  ManagerLayoutAdvertisementsRoute: typeof ManagerLayoutAdvertisementsRoute
  ManagerLayoutLocationsRoute: typeof ManagerLayoutLocationsRoute
  ManagerLayoutPartnerRequestsRoute: typeof ManagerLayoutPartnerRequestsRoute
  ManagerLayoutPoisRoute: typeof ManagerLayoutPoisRouteWithChildren
  ManagerLayoutIndexRoute: typeof ManagerLayoutIndexRoute
}

const ManagerLayoutRouteChildren: ManagerLayoutRouteChildren = {
  ManagerLayoutAdvertisementsRoute: ManagerLayoutAdvertisementsRoute,
  ManagerLayoutLocationsRoute: ManagerLayoutLocationsRoute,
  ManagerLayoutPartnerRequestsRoute: ManagerLayoutPartnerRequestsRoute,
  ManagerLayoutPoisRoute: ManagerLayoutPoisRouteWithChildren,
  ManagerLayoutIndexRoute: ManagerLayoutIndexRoute,
}

const ManagerLayoutRouteWithChildren = ManagerLayoutRoute._addFileChildren(
  ManagerLayoutRouteChildren,
)

interface PartnerLayoutRouteChildren {
  PartnerLayoutAdvertisementRoute: typeof PartnerLayoutAdvertisementRoute
  PartnerLayoutHistoryRoute: typeof PartnerLayoutHistoryRoute
  PartnerLayoutPackagesRoute: typeof PartnerLayoutPackagesRoute
  PartnerLayoutPoiRoute: typeof PartnerLayoutPoiRoute
  PartnerLayoutProfileRoute: typeof PartnerLayoutProfileRoute
  PartnerLayoutStatsRoute: typeof PartnerLayoutStatsRoute
  PartnerLayoutIndexRoute: typeof PartnerLayoutIndexRoute
}

const PartnerLayoutRouteChildren: PartnerLayoutRouteChildren = {
  PartnerLayoutAdvertisementRoute: PartnerLayoutAdvertisementRoute,
  PartnerLayoutHistoryRoute: PartnerLayoutHistoryRoute,
  PartnerLayoutPackagesRoute: PartnerLayoutPackagesRoute,
  PartnerLayoutPoiRoute: PartnerLayoutPoiRoute,
  PartnerLayoutProfileRoute: PartnerLayoutProfileRoute,
  PartnerLayoutStatsRoute: PartnerLayoutStatsRoute,
  PartnerLayoutIndexRoute: PartnerLayoutIndexRoute,
}

const PartnerLayoutRouteWithChildren = PartnerLayoutRoute._addFileChildren(
  PartnerLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ManagerLayoutRoute: ManagerLayoutRouteWithChildren,
  ManagerLoginRoute: ManagerLoginRoute,
  PartnerLayoutRoute: PartnerLayoutRouteWithChildren,
  PartnerLoginRoute: PartnerLoginRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
